// 临时的内存用户存储（用于演示）
export const memoryUsers: Record<string, any> = {
  admin: {
    id: 1,
    username: 'admin',
    password: 'mc6668',
    name: '管理员',
    role: 'admin',
    position: '管理员',
    phone: '15392966668',
    department_id: 1,
    department_name: '五金事业部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  zlx8011: {
    id: 2,
    username: 'zlx8011',
    password: 'zlx8011',
    name: '张立兴',
    role: 'user',
    position: '总经理',
    phone: '18210108011',
    department_id: 1,
    department_name: '五金事业部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  mc8388: {
    id: 3,
    username: 'mc8388',
    password: 'mc8388',
    name: '毛闯',
    role: 'user',
    position: '项目总监',
    phone: '18576698388',
    department_id: 2,
    department_name: '项目部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  yj8354: {
    id: 4,
    username: 'yj8354',
    password: 'yj8354',
    name: '杨佳',
    role: 'user',
    position: '业务总监',
    phone: '13001059354',
    department_id: 4,
    department_name: '销售部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  ll6762: {
    id: 5,
    username: 'll6762',
    password: 'll6762',
    name: '李林',
    role: 'user',
    position: '项目助理',
    phone: '13182326762',
    department_id: 2,
    department_name: '项目部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  syw9872: {
    id: 6,
    username: 'syw9872',
    password: 'syw9872',
    name: '孙运伟',
    role: 'user',
    position: '技术服务组长',
    phone: '19862819872',
    department_id: 6,
    department_name: '技术服务一组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  dc5373: {
    id: 7,
    username: 'dc5373',
    password: 'dc5373',
    name: '代超',
    role: 'user',
    position: '技术服务组长',
    phone: '15838165373',
    department_id: 7,
    department_name: '技术服务二组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  zjy7530: {
    id: 8,
    username: 'zjy7530',
    password: 'zjy7530',
    name: '祖加友',
    role: 'user',
    position: '技术服务组长',
    phone: '18702487530',
    department_id: 8,
    department_name: '技术服务三组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  ldy3789: {
    id: 9,
    username: 'ldy3789',
    password: 'ldy3789',
    name: '刘东亚',
    role: 'user',
    position: '生产主管',
    phone: '13791723789',
    department_id: 5,
    department_name: '生产部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  dtb7985: {
    id: 10,
    username: 'dtb7985',
    password: 'dtb7985',
    name: '邓天宝',
    role: 'user',
    position: '项目助理',
    phone: '13317107985',
    department_id: 2,
    department_name: '项目部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  wq4462: {
    id: 11,
    username: 'wq4462',
    password: 'wq4462',
    name: '魏琴',
    role: 'user',
    position: '运营主管',
    phone: '18201004462',
    department_id: 3,
    department_name: '运营部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  mcc0036: {
    id: 12,
    username: 'mcc0036',
    password: 'mcc0036',
    name: '孟春婵',
    role: 'user',
    position: '运营总监',
    phone: '18210100036',
    department_id: 3,
    department_name: '运营部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  lt1382: {
    id: 13,
    username: 'lt1382',
    password: 'lt1382',
    name: '李涛',
    role: 'user',
    position: '技术工程师',
    phone: '15067981382',
    department_id: 7,
    department_name: '技术服务二组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  zgc12176: {
    id: 14,
    username: 'zgc12176',
    password: 'zgc12176',
    name: '周广朝',
    role: 'user',
    position: '技术工程师',
    phone: '16652212176',
    department_id: 7,
    department_name: '技术服务二组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  gaj0683: {
    id: 15,
    username: 'gaj0683',
    password: 'gaj0683',
    name: '郭澳杰',
    role: 'user',
    position: '技术工程师',
    phone: '13323910683',
    department_id: 6,
    department_name: '技术服务一组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  lzm8863: {
    id: 16,
    username: 'lzm8863',
    password: 'lzm8863',
    name: '罗子蒙',
    role: 'user',
    position: '技术工程师',
    phone: '17355728863',
    department_id: 6,
    department_name: '技术服务一组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  cf5452: {
    id: 17,
    username: 'cf5452',
    password: 'cf5452',
    name: '陈飞',
    role: 'user',
    position: '技术工程师',
    phone: '18358955452',
    department_id: 7,
    department_name: '技术服务二组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  yzy3397: {
    id: 18,
    username: 'yzy3397',
    password: 'yzy3397',
    name: '严正园',
    role: 'user',
    position: '技术工程师',
    phone: '13580913397',
    department_id: 7,
    department_name: '技术服务二组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  sxg5580: {
    id: 19,
    username: 'sxg5580',
    password: 'sxg5580',
    name: '孙晓刚',
    role: 'user',
    position: '技术工程师',
    phone: '19158345580',
    department_id: 7,
    department_name: '技术服务二组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  ltc7775: {
    id: 20,
    username: 'ltc7775',
    password: 'ltc7775',
    name: '卢腾超',
    role: 'user',
    position: '技术工程师',
    phone: '15988537775',
    department_id: 8,
    department_name: '技术服务三组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  ldj0329: {
    id: 21,
    username: 'ldj0329',
    password: 'ldj0329',
    name: '李东杰',
    role: 'user',
    position: '技术工程师',
    phone: '17516520329',
    department_id: 8,
    department_name: '技术服务三组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  yf6605: {
    id: 22,
    username: 'yf6605',
    password: 'yf6605',
    name: '杨帆',
    role: 'user',
    position: '技术工程师',
    phone: '17320276605',
    department_id: 8,
    department_name: '技术服务三组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  cxg9271: {
    id: 23,
    username: 'cxg9271',
    password: 'cxg9271',
    name: '曹小刚',
    role: 'user',
    position: '技术工程师',
    phone: '18334059271',
    department_id: 8,
    department_name: '技术服务三组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
};

// 导出的内存用户数组（用于列表查询）
export const memoryUsersArray = Object.values(memoryUsers);

// 内存用户数组的引用（用于动态更新）
export let memoryUsersList = [...memoryUsersArray];

// 导出内存部门列表
export const memoryDepartments = [
  {
    id: 1,
    name: '五金事业部',
    code: 'HARDWARE',
    parent_id: null,
    sort_order: 1,
    is_disabled: false,
  },
  {
    id: 2,
    name: '项目部',
    code: 'PROJECT',
    parent_id: 1,
    sort_order: 10,
    is_disabled: false,
  },
  {
    id: 3,
    name: '运营部',
    code: 'OPERATION',
    parent_id: 1,
    sort_order: 20,
    is_disabled: false,
  },
  {
    id: 4,
    name: '销售部',
    code: 'SALES',
    parent_id: 1,
    sort_order: 30,
    is_disabled: false,
  },
  {
    id: 5,
    name: '生产部',
    code: 'PRODUCTION',
    parent_id: 1,
    sort_order: 40,
    is_disabled: false,
  },
  {
    id: 6,
    name: '技术服务一组',
    code: 'TS_GROUP_1',
    parent_id: 2,
    sort_order: 1,
    is_disabled: false,
  },
  {
    id: 7,
    name: '技术服务二组',
    code: 'TS_GROUP_2',
    parent_id: 2,
    sort_order: 2,
    is_disabled: false,
  },
  {
    id: 8,
    name: '技术服务三组',
    code: 'TS_GROUP_3',
    parent_id: 2,
    sort_order: 3,
    is_disabled: false,
  },
];
// 预置合同数据
export const memoryContracts = [
  {
    id: 1,
    contract_number: 'HT-2026-001',
    contract_name: 'IT设备采购合同',
    customer_id: 1,
    customer_name: '北京科技有限公司',
    business_manager: '张经理',
    contract_amount: 150000,
    sign_date: '2026-01-15',
    acceptance_date: '2026-02-15',
    warranty_end_date: '2027-01-15',
    status: 'active',
    remarks: '设备全部验收合格，运行稳定',
    tags: ['IT设备', '采购'],
    addresses: ['北京市海淀区中关村大街1号'],
    contacts: [
      { id: 1, name: '李总', phone: '13800138001', position: '总经理' },
      { id: 2, name: '王工', phone: '13800138002', position: '技术总监' },
    ],
    device_count: 5,
    work_order_count: 2,
    created_at: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 2,
    contract_number: 'HT-2026-002',
    contract_name: '软件运维服务合同',
    customer_id: 2,
    customer_name: '上海贸易集团',
    business_manager: '陈经理',
    contract_amount: 80000,
    sign_date: '2026-02-01',
    acceptance_date: '2026-02-15',
    warranty_end_date: '2027-02-01',
    status: 'active',
    remarks: '系统运维服务，7x24小时响应',
    tags: ['软件', '运维'],
    addresses: ['上海市浦东新区陆家嘴环路1000号'],
    contacts: [
      { id: 3, name: '赵总', phone: '13900139001', position: '董事长' },
    ],
    device_count: 0,
    work_order_count: 3,
    created_at: '2026-02-01T10:00:00.000Z',
  },
  {
    id: 3,
    contract_number: 'HT-2026-003',
    contract_name: '网络设备升级项目',
    customer_id: 3,
    customer_name: '深圳电子实业',
    business_manager: '刘经理',
    contract_amount: 250000,
    sign_date: '2026-03-10',
    acceptance_date: '',
    warranty_end_date: '2027-03-10',
    status: 'pending',
    remarks: '项目进行中，待验收',
    tags: ['网络', '升级'],
    addresses: ['深圳市南山区科技园南区'],
    contacts: [
      { id: 4, name: '孙工', phone: '13700137001', position: '项目经理' },
      { id: 5, name: '周工', phone: '13700137002', position: '系统工程师' },
    ],
    device_count: 8,
    work_order_count: 1,
    created_at: '2026-03-10T10:00:00.000Z',
  },
];

// 预置设备数据
export const memoryDevices = [
  {
    id: 1,
    device_number: 'D0001',
    device_name: '智能焊接机器人-X100',
    device_model: 'X100-PRO',
    factory_serial_number: 'SN202401150001',
    device_type: '智能焊接',
    customer_id: 1,
    customer_name: '北京科技有限公司',
    factory_date: '2024-01-15',
    acceptance_date: '2024-02-15',
    warranty_end_date: '2025-01-15',
    status: '正常',
    contract_name: '焊接设备采购合同-2024-001',
    contract_number: 'HT-2024-001',
    location: '生产车间A区-01号工位',
    qr_code: 'QR-2024-001',
    photos: [],
    remarks: '首次安装调试完成，运行正常',
  },
  {
    id: 2,
    device_number: 'D0002',
    device_name: '智能测温仪-T500',
    device_model: 'T500-ULTRA',
    factory_serial_number: 'SN202402200002',
    device_type: '智能测温',
    customer_id: 2,
    customer_name: '上海贸易集团',
    factory_date: '2024-02-20',
    acceptance_date: '2024-03-20',
    warranty_end_date: '2025-02-20',
    status: '正常',
    contract_name: '测温设备采购合同-2024-002',
    contract_number: 'HT-2024-002',
    location: '质检中心-03号检测台',
    qr_code: 'QR-2024-002',
    photos: [],
    remarks: '精度校准完成，检测范围-50℃至500℃',
  },
  {
    id: 3,
    device_number: 'D0003',
    device_name: '外观品检机-AI200',
    device_model: 'AI200-SMART',
    factory_serial_number: 'SN202403100003',
    device_type: '外观品检',
    customer_id: 3,
    customer_name: '深圳电子实业',
    factory_date: '2024-03-10',
    acceptance_date: '2024-04-10',
    warranty_end_date: '2025-03-10',
    status: '维修中',
    contract_name: '品检设备采购合同-2024-003',
    contract_number: 'HT-2024-003',
    location: '质检车间-B区-05号工位',
    qr_code: 'QR-2024-003',
    photos: [],
    remarks: '视觉系统故障，待维修更换',
  },
];

// 预置工单数据
export const memoryWorkOrders = [
  {
    id: 1,
    order_no: 'WO202501220001',
    title: '电梯控制板故障，需要更换主板',
    description: '电梯控制板故障，需要更换主板',
    customer_id: 1,
    device_id: 1,
    type: '维修',
    priority: 'high',
    status: 'pending',
    stage: 'assigned',
    plan_hours: 4.0,
    is_charged: true,
    quoted_price: 5800.00,
    assignee_id: 2,
    created_by: 1,
    customer_name: '北京科技有限公司',
    device_name: 'A栋电梯1号',
    assignee_name: '李明',
    created_at: '2025-01-22 09:30:00',
  },
  {
    id: 2,
    order_no: 'WO202501220002',
    title: '电梯门系统异常，需调整门机参数',
    description: '电梯门系统异常，需调整门机参数',
    customer_id: 2,
    device_id: 2,
    type: '维修',
    priority: 'high',
    status: 'processing',
    stage: 'processing',
    plan_hours: 3.0,
    is_charged: true,
    quoted_price: 3200.00,
    assignee_id: 3,
    created_by: 1,
    customer_name: '上海贸易集团',
    device_name: 'B栋电梯2号',
    assignee_name: '王伟',
    created_at: '2025-01-22 10:15:00',
  },
  {
    id: 3,
    order_no: 'WO202501220003',
    title: '年度例行保养检查',
    description: '年度例行保养检查',
    customer_id: 1,
    device_id: 1,
    type: '保养',
    priority: 'normal',
    status: 'completed',
    stage: 'completed',
    plan_hours: 2.0,
    is_charged: false,
    quoted_price: 0.00,
    assignee_id: 2,
    created_by: 1,
    customer_name: '北京科技有限公司',
    device_name: 'A栋电梯1号',
    assignee_name: '李明',
    created_at: '2025-01-22 11:00:00',
  },
  {
    id: 4,
    order_no: 'WO202501220004',
    title: '电梯空调系统安装',
    description: '电梯空调系统安装',
    customer_id: 3,
    device_id: 3,
    type: '安装',
    priority: 'high',
    status: 'pending',
    stage: 'pending',
    plan_hours: 8.0,
    is_charged: true,
    quoted_price: 15000.00,
    assignee_id: null,
    created_by: 1,
    customer_name: '深圳电子实业',
    device_name: 'C栋电梯3号',
    assignee_name: null,
    created_at: '2025-01-22 13:30:00',
  },
  {
    id: 5,
    order_no: 'WO202501220005',
    title: '电梯控制系统升级改造',
    description: '电梯控制系统升级改造',
    customer_id: 2,
    device_id: 2,
    type: '其他',
    priority: 'high',
    status: 'processing',
    stage: 'processing',
    plan_hours: 12.0,
    is_charged: true,
    quoted_price: 28000.00,
    assignee_id: 3,
    created_by: 1,
    customer_name: '上海贸易集团',
    device_name: 'B栋电梯2号',
    assignee_name: '王伟',
    created_at: '2025-01-22 14:45:00',
  },
];


// 预置会议纪要数据
export const memoryMeetingMinutes = [
  {
    id: 1,
    meeting_name: '项目启动会议',
    meeting_type: 'other',
    meeting_date: '2026-03-15',
    meeting_location: '会议室A',
    attendees: '李四,王五,赵六',
    host: '张三',
    recorder: '张三',
    topics: '讨论项目整体规划和分工安排，确定项目里程碑和时间节点。',
    key_points: '1. 项目整体周期为3个月\n2. 每周五召开进度会议\n3. 技术方案下周确定',
    summary: '完成技术方案设计，准备项目资源',
    file_url: null,
    customer_id: null,
    project_id: null,
    viewable_users: null,
    tags: [],
    created_at: '2026-03-15T10:00:00.000Z',
    updated_at: '2026-03-15T10:00:00.000Z',
  },
  {
    id: 2,
    meeting_name: '技术方案评审会',
    meeting_type: 'technical',
    meeting_date: '2026-03-20',
    meeting_location: '会议室B',
    attendees: '张三,王五,刘七',
    host: '李四',
    recorder: '李四',
    topics: '评审技术方案，确认可行性和风险点。',
    key_points: '1. 采用微服务架构\n2. 使用容器化部署\n3. 数据库选用PostgreSQL',
    summary: '开始系统设计和开发',
    file_url: null,
    customer_id: null,
    project_id: null,
    viewable_users: null,
    tags: [],
    created_at: '2026-03-20T14:00:00.000Z',
    updated_at: '2026-03-20T14:00:00.000Z',
  },
  {
    id: 3,
    meeting_name: '月度工作总结会议',
    meeting_type: 'regular',
    meeting_date: '2026-04-01',
    meeting_location: '会议室A',
    attendees: '全员',
    host: '王五',
    recorder: '王五',
    topics: '总结上月工作完成情况，制定本月工作计划。',
    key_points: '1. 上月目标完成率85%\n2. 本月重点推进客户需求',
    summary: '跟进重点客户，优化服务流程',
    file_url: null,
    customer_id: null,
    project_id: null,
    viewable_users: null,
    tags: [],
    created_at: '2026-04-01T09:00:00.000Z',
    updated_at: '2026-04-01T09:00:00.000Z',
  },
];

export const memorySessions: any[] = [];

// 设备履历列表
export const deviceHistoryList = [
  {
    id: 1,
    device_id: 1,
    type: '保养',
    title: '设备保养',
    description: '对设备进行全面清洁和润滑',
    result: '完成',
    operator: '张师傅',
    created_at: '2024-05-01 10:00:00',
    updated_at: '2024-05-01 10:00:00',
  },
  {
    id: 2,
    device_id: 1,
    type: '维修',
    title: '设备维修',
    description: '更换磨损零件',
    result: '完成',
    operator: '李师傅',
    created_at: '2024-05-10 14:30:00',
    updated_at: '2024-05-10 14:30:00',
  },
  {
    id: 3,
    device_id: 1,
    type: '巡检',
    title: '设备巡检',
    description: '例行安全检查',
    result: '通过',
    operator: '王师傅',
    created_at: '2024-05-15 09:00:00',
    updated_at: '2024-05-15 09:00:00',
  },
];

export function getUserByUsername(username: string) {
  const user = memoryUsers[username as keyof typeof memoryUsers];
  return user || null;
}

export function createSession(userId: number, sessionId: string, deviceId: string) {
  const session = {
    id: memorySessions.length + 1,
    user_id: userId,
    session_id: sessionId,
    device_id: deviceId,
    login_time: new Date(),
    last_active_time: new Date(),
    is_active: true,
  };
  memorySessions.push(session);
  return session;
}

export function getActiveSessionCount(userId: number) {
  return memorySessions.filter(
    s => s.user_id === userId && s.is_active
  ).length;
}

export function deactivateOldestSession(userId: number) {
  const oldestSession = memorySessions
    .filter(s => s.user_id === userId && s.is_active)
    .sort((a, b) => new Date(a.login_time).getTime() - new Date(b.login_time).getTime())[0];
  if (oldestSession) {
    oldestSession.is_active = false;
  }
}

// 预置设备履历数据
export const memoryDeviceHistory = [
  {
    id: 1,
    device_id: 1,
    type: '保养',
    description: '例行保养，更换润滑油',
    result: '完成',
    date: '2025-01-15',
    operator: '张师傅',
  },
  {
    id: 2,
    device_id: 1,
    type: '维修',
    description: '变频器故障，更换变频器模块',
    result: '完成',
    date: '2025-01-20',
    operator: '李师傅',
  },
  {
    id: 3,
    device_id: 1,
    type: '巡检',
    description: '日常巡检，检查运行状态',
    result: '正常',
    date: '2025-02-01',
    operator: '王师傅',
  },
  {
    id: 4,
    device_id: 2,
    type: '保养',
    description: '年度保养，清洗过滤网',
    result: '完成',
    date: '2025-01-10',
    operator: '张师傅',
  },
  {
    id: 5,
    device_id: 2,
    type: '巡检',
    description: '月度巡检，检测温湿度',
    result: '正常',
    date: '2025-02-05',
    operator: '王师傅',
  },
];
