// 临时的内存用户存储（用于演示）
export const memoryUsers: Record<string, any> = {
  admin: {
    id: 1,
    username: 'admin',
    password: 'mc6668',
    name: '管理员',
    role: 'admin',
    position: '管理员',
    phone: '15392966668',
    department_id: 1,
    department_name: '五金事业部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  zlx8011: {
    id: 2,
    username: 'zlx8011',
    password: 'zlx8011',
    name: '张立兴',
    role: 'user',
    position: '总经理',
    phone: '18210108011',
    department_id: 1,
    department_name: '五金事业部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  mc8388: {
    id: 3,
    username: 'mc8388',
    password: 'mc8388',
    name: '毛闯',
    role: 'user',
    position: '项目总监',
    phone: '18576698388',
    department_id: 2,
    department_name: '项目部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  yj8354: {
    id: 4,
    username: 'yj8354',
    password: 'yj8354',
    name: '杨佳',
    role: 'user',
    position: '业务总监',
    phone: '13001059354',
    department_id: 4,
    department_name: '销售部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  ll6762: {
    id: 5,
    username: 'll6762',
    password: 'll6762',
    name: '李林',
    role: 'user',
    position: '项目助理',
    phone: '13182326762',
    department_id: 2,
    department_name: '项目部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  syw9872: {
    id: 6,
    username: 'syw9872',
    password: 'syw9872',
    name: '孙运伟',
    role: 'user',
    position: '技术服务组长',
    phone: '19862819872',
    department_id: 6,
    department_name: '技术服务一组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  dc5373: {
    id: 7,
    username: 'dc5373',
    password: 'dc5373',
    name: '代超',
    role: 'user',
    position: '技术服务组长',
    phone: '15838165373',
    department_id: 7,
    department_name: '技术服务二组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  zjy7530: {
    id: 8,
    username: 'zjy7530',
    password: 'zjy7530',
    name: '祖加友',
    role: 'user',
    position: '技术服务组长',
    phone: '18702487530',
    department_id: 8,
    department_name: '技术服务三组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  ldy3789: {
    id: 9,
    username: 'ldy3789',
    password: 'ldy3789',
    name: '刘东亚',
    role: 'user',
    position: '生产主管',
    phone: '13791723789',
    department_id: 5,
    department_name: '生产部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  dtb7985: {
    id: 10,
    username: 'dtb7985',
    password: 'dtb7985',
    name: '邓天宝',
    role: 'user',
    position: '项目助理',
    phone: '13317107985',
    department_id: 2,
    department_name: '项目部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  wq4462: {
    id: 11,
    username: 'wq4462',
    password: 'wq4462',
    name: '魏琴',
    role: 'user',
    position: '运营主管',
    phone: '18201004462',
    department_id: 3,
    department_name: '运营部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  mcc0036: {
    id: 12,
    username: 'mcc0036',
    password: 'mcc0036',
    name: '孟春婵',
    role: 'user',
    position: '运营总监',
    phone: '18210100036',
    department_id: 3,
    department_name: '运营部',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  lt1382: {
    id: 13,
    username: 'lt1382',
    password: 'lt1382',
    name: '李涛',
    role: 'user',
    position: '技术工程师',
    phone: '15067981382',
    department_id: 7,
    department_name: '技术服务二组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  zgc12176: {
    id: 14,
    username: 'zgc12176',
    password: 'zgc12176',
    name: '周广朝',
    role: 'user',
    position: '技术工程师',
    phone: '16652212176',
    department_id: 7,
    department_name: '技术服务二组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  gaj0683: {
    id: 15,
    username: 'gaj0683',
    password: 'gaj0683',
    name: '郭澳杰',
    role: 'user',
    position: '技术工程师',
    phone: '13323910683',
    department_id: 6,
    department_name: '技术服务一组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  lzm8863: {
    id: 16,
    username: 'lzm8863',
    password: 'lzm8863',
    name: '罗子蒙',
    role: 'user',
    position: '技术工程师',
    phone: '17355728863',
    department_id: 6,
    department_name: '技术服务一组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  cf5452: {
    id: 17,
    username: 'cf5452',
    password: 'cf5452',
    name: '陈飞',
    role: 'user',
    position: '技术工程师',
    phone: '18358955452',
    department_id: 7,
    department_name: '技术服务二组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  yzy3397: {
    id: 18,
    username: 'yzy3397',
    password: 'yzy3397',
    name: '严正园',
    role: 'user',
    position: '技术工程师',
    phone: '13580913397',
    department_id: 7,
    department_name: '技术服务二组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  sxg5580: {
    id: 19,
    username: 'sxg5580',
    password: 'sxg5580',
    name: '孙晓刚',
    role: 'user',
    position: '技术工程师',
    phone: '19158345580',
    department_id: 7,
    department_name: '技术服务二组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  ltc7775: {
    id: 20,
    username: 'ltc7775',
    password: 'ltc7775',
    name: '卢腾超',
    role: 'user',
    position: '技术工程师',
    phone: '15988537775',
    department_id: 8,
    department_name: '技术服务三组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  ldj0329: {
    id: 21,
    username: 'ldj0329',
    password: 'ldj0329',
    name: '李东杰',
    role: 'user',
    position: '技术工程师',
    phone: '17516520329',
    department_id: 8,
    department_name: '技术服务三组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  yf6605: {
    id: 22,
    username: 'yf6605',
    password: 'yf6605',
    name: '杨帆',
    role: 'user',
    position: '技术工程师',
    phone: '17320276605',
    department_id: 8,
    department_name: '技术服务三组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  cxg9271: {
    id: 23,
    username: 'cxg9271',
    password: 'cxg9271',
    name: '曹小刚',
    role: 'user',
    position: '技术工程师',
    phone: '18334059271',
    department_id: 8,
    department_name: '技术服务三组',
    avatar: null,
    signature: null,
    is_disabled: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
};

// 导出的内存用户数组（用于列表查询）
export const memoryUsersArray = Object.values(memoryUsers);

// 内存用户数组的引用（用于动态更新）
export let memoryUsersList = [...memoryUsersArray];

// 导出内存部门列表
export const memoryDepartments = [
  {
    id: 1,
    name: '五金事业部',
    code: 'HARDWARE',
    parent_id: null,
    sort_order: 1,
    is_disabled: false,
  },
  {
    id: 2,
    name: '项目部',
    code: 'PROJECT',
    parent_id: 1,
    sort_order: 10,
    is_disabled: false,
  },
  {
    id: 3,
    name: '运营部',
    code: 'OPERATION',
    parent_id: 1,
    sort_order: 20,
    is_disabled: false,
  },
  {
    id: 4,
    name: '销售部',
    code: 'SALES',
    parent_id: 1,
    sort_order: 30,
    is_disabled: false,
  },
  {
    id: 5,
    name: '生产部',
    code: 'PRODUCTION',
    parent_id: 1,
    sort_order: 40,
    is_disabled: false,
  },
  {
    id: 6,
    name: '技术服务一组',
    code: 'TS_GROUP_1',
    parent_id: 2,
    sort_order: 1,
    is_disabled: false,
  },
  {
    id: 7,
    name: '技术服务二组',
    code: 'TS_GROUP_2',
    parent_id: 2,
    sort_order: 2,
    is_disabled: false,
  },
  {
    id: 8,
    name: '技术服务三组',
    code: 'TS_GROUP_3',
    parent_id: 2,
    sort_order: 3,
    is_disabled: false,
  },
];

// 预置会议纪要数据
export const memoryMeetingMinutes = [
  {
    id: 1,
    title: '项目启动会议',
    meeting_date: '2026-03-15',
    location: '会议室A',
    host: '张三',
    participants: '李四,王五,赵六',
    content: '讨论项目整体规划和分工安排，确定项目里程碑和时间节点。',
    decisions: '1. 项目整体周期为3个月\n2. 每周五召开进度会议\n3. 技术方案下周确定',
    next_steps: '完成技术方案设计，准备项目资源',
    created_at: '2026-03-15T10:00:00.000Z',
    updated_at: '2026-03-15T10:00:00.000Z',
  },
  {
    id: 2,
    title: '技术方案评审会',
    meeting_date: '2026-03-20',
    location: '会议室B',
    host: '李四',
    participants: '张三,王五,刘七',
    content: '评审技术方案，确认可行性和风险点。',
    decisions: '1. 采用微服务架构\n2. 使用容器化部署\n3. 数据库选用PostgreSQL',
    next_steps: '开始系统设计和开发',
    created_at: '2026-03-20T14:00:00.000Z',
    updated_at: '2026-03-20T14:00:00.000Z',
  },
  {
    id: 3,
    title: '月度工作总结会议',
    meeting_date: '2026-04-01',
    location: '会议室A',
    host: '王五',
    participants: '全员',
    content: '总结上月工作完成情况，制定本月工作计划。',
    decisions: '1. 上月目标完成率85%\n2. 本月重点推进客户需求',
    next_steps: '跟进重点客户，优化服务流程',
    created_at: '2026-04-01T09:00:00.000Z',
    updated_at: '2026-04-01T09:00:00.000Z',
  },
];

export const memorySessions: any[] = [];

export function getUserByUsername(username: string) {
  const user = memoryUsers[username as keyof typeof memoryUsers];
  return user || null;
}

export function createSession(userId: number, sessionId: string, deviceId: string) {
  const session = {
    id: memorySessions.length + 1,
    user_id: userId,
    session_id: sessionId,
    device_id: deviceId,
    login_time: new Date(),
    last_active_time: new Date(),
    is_active: true,
  };
  memorySessions.push(session);
  return session;
}

export function getActiveSessionCount(userId: number) {
  return memorySessions.filter(
    s => s.user_id === userId && s.is_active
  ).length;
}

export function deactivateOldestSession(userId: number) {
  const oldestSession = memorySessions
    .filter(s => s.user_id === userId && s.is_active)
    .sort((a, b) => new Date(a.login_time).getTime() - new Date(b.login_time).getTime())[0];
  if (oldestSession) {
    oldestSession.is_active = false;
  }
}
